apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: contact-system
  labels:
    app: postgres-db
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  PGDATA: "/var/lib/postgresql/data/pgdata"