apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: contact-system
  labels:
    app: postgres-db
    tier: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres-db