apiVersion: v1
kind: ConfigMap
metadata:
  name: contact-app-config
  namespace: contact-system
  labels:
    app: contact-app
data:
  DB_HOST: "postgres_db"
  DB_PORT: "5432"
  POSTGRES_DB: "postgres"
  DB_USERNAME: "postgres"
  TEMPLATE_STYLE: "random"
  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "3000"
  FLASK_DEBUG: "false"
  TEMPLATES_DIR: "templates"
  OUTPUT_DIR: "static/generated"